version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - /app/node_modules/
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: ./.docker/php
      args:
        - WITH_XDEBUG=true
    volumes:
      - ./app:/app
      # Prevent packages from being added to the container
      # - /app/node_modules/
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - PHP_IDE_CONFIG
      - XDEBUG_CONFIG
    depends_on:
      - db

  db:
    image: mysql:5.7
    working_dir: /app
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "8002:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: $MYSQL_USER
      PMA_PASSWORD: $MYSQL_PASSWORD
    depends_on:
      - db
    ports:
      - "80:80"

volumes:
  db-data:
